spring:
  web:
    locale-resolver: fixed
    locale: pt_BR

  datasource:
    url: jdbc:postgresql://172.23.71.93:5432/Demo-Park-Telegram
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: none

    open-in-view: true

    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /docs-park.html

  api-docs:
    path: /docs-park

  packages-to-scan: org.gabrielbarrilli.securitytelegram.web.controller