#LOCALE
spring:
  web:
    locale-resolver: fixed
    locale: pt_BR

  datasource:
    url: jdbc:postgresql://localhost:5432/Demo-Park-Telegram
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: none

    open-in-view: true